import asyncio
import uuid

import streamlit as st
from langchain_core.messages import HumanMessage, SystemMessage

from runnable import get_runnable


SYSTEM_PROMPT = """
You are a meeting notes assistant. Your primary function is to answer questions by retrieving and synthesizing information from the meeting notes database.

RULES:
1. You MUST call the query_documents tool for every user question before providing an answer. Do not answer from memory or prior conversation context.
2. Base your answer strictly on the retrieved documents. Do not introduce, infer, or fabricate information that is not explicitly stated in the source material.
3. When the retrieved documents contain relevant information, synthesize a comprehensive answer drawing from ALL returned documents. A single query may return documents from different meetings -- combine them into a unified response.
4. Reference specific meeting names when available in the source metadata (e.g., "In the Database Optimization Discussion meeting...").
5. List all relevant decisions, action items, and participants mentioned in the documents.
6. Only say "I don't know" or "I couldn't find that information" if the retrieved documents genuinely contain no relevant information after the search.
"""


@st.cache_resource
def chatbot():
    """
    Create and cache the LangGraph chatbot instance.

    Streamlit caches this object so the graph is created only once,
    even when the app reruns after each user interaction.
    """
    return get_runnable()

# Create the chatbot
app = chatbot()

# Create a unique conversation thread.
# LangGraph uses the thread ID to maintain conversation memory.
THREAD_ID = str(uuid.uuid4())


async def ask_llm(prompt: str):
    """
    Send the user's prompt to the LangGraph agent and return
    the assistant's final response.

    Args:
        prompt (str): User's input message.

    Returns:
        str: Assistant's response.
    """
    config = {
        "configurable": {
            "thread_id": THREAD_ID
        }
    }

    result = await app.ainvoke(
        {
            "messages": [
                SystemMessage(content=SYSTEM_PROMPT),
                HumanMessage(content=prompt),
            ]
        },
        config=config,
    )

    # Return the last message generated by the agent
    return result["messages"][-1].content


async def main():
    """
    Main Streamlit application.

    Responsibilities:
    1. Display the application title.
    2. Store chat history in Streamlit session state.
    3. Display previous messages.
    4. Accept new user input.
    5. Send the input to the LangGraph agent.
    6. Display the assistant's response.
    """
    st.title("🤖 Meeting Notes Agent Powered By Langraph")

    # Initialize chat history on the first run
    if "history" not in st.session_state:
        st.session_state.history = []

    # Display all previous messages
    for role, message in st.session_state.history:
        with st.chat_message(role):
            st.markdown(message)

    # Wait for the user to enter a message
    if prompt := st.chat_input("Ask me anything..."):

        # Save and display the user's message
        st.session_state.history.append(("user", prompt))

        with st.chat_message("user"):
            st.markdown(prompt)

        # Get the assistant's response
        with st.chat_message("assistant"):
            response = await ask_llm(prompt)
            st.markdown(response)

        # Save the assistant's response
        st.session_state.history.append(("assistant", response))


if __name__ == "__main__":
    # Start the Streamlit application
    asyncio.run(main())