import asyncio
import uuid

import streamlit as st
from langchain_core.messages import HumanMessage, SystemMessage

from runnable import get_runnable


@st.cache_resource
def chatbot():
    """
    Create and cache the LangGraph chatbot instance.

    Streamlit caches this object so the graph is created only once,
    even when the app reruns after each user interaction.
    """
    return get_runnable()


# Create the chatbot
app = chatbot()

# Create a unique conversation thread.
# LangGraph uses the thread ID to maintain conversation memory.
THREAD_ID = str(uuid.uuid4())


async def ask_llm(prompt: str):
    """
    Send the user's prompt to the LangGraph agent and return
    the assistant's final response.

    Args:
        prompt (str): User's input message.

    Returns:
        str: Assistant's response.
    """
    config = {
        "configurable": {
            "thread_id": THREAD_ID
        }
    }

    SYSTEM_PROMPT = """
You are a helpful AI assistant.
Use the available tools whenever they are helpful.
Answer clearly and concisely.
"""

    result = await app.ainvoke(
        {
            "messages": [
                HumanMessage(content=prompt),
                SystemMessage(content=SYSTEM_PROMPT)
            ]
        },
        config=config,
    )

    # Return the last message generated by the agent
    return result["messages"][-1].content


async def main():
    """
    Main Streamlit application.

    Responsibilities:
    1. Display the application title.
    2. Store chat history in Streamlit session state.
    3. Display previous messages.
    4. Accept new user input.
    5. Send the input to the LangGraph agent.
    6. Display the assistant's response.
    """
    st.title("🤖 LangGraph Demo")

    # Initialize chat history on the first run
    if "history" not in st.session_state:
        st.session_state.history = []

    # Display all previous messages
    for role, message in st.session_state.history:
        with st.chat_message(role):
            st.markdown(message)

    # Wait for the user to enter a message
    if prompt := st.chat_input("Ask me anything..."):

        # Save and display the user's message
        st.session_state.history.append(("user", prompt))

        with st.chat_message("user"):
            st.markdown(prompt)

        # Get the assistant's response
        with st.chat_message("assistant"):
            response = await ask_llm(prompt)
            st.markdown(response)

        # Save the assistant's response
        st.session_state.history.append(("assistant", response))


if __name__ == "__main__":
    # Start the Streamlit application
    asyncio.run(main())